apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  labels:
    app: nextjs-app
spec:
  replicas: 3 # Number of replicas (pods)
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-app
          image: anshik12/ideserver:frontend
          ports:
            - containerPort: 3000 # Port your app listens on
          env:
            - name: NODE_ENV
              value: "production"
            - name: BACKEND_URL
              value: "https://api.iamanshik.online"
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-app
  labels:
    app: nextjs-app
spec:
  type: ClusterIP # Exposes the service internally within the cluster
  ports:
    - port: 3000 # Port exposed by the service
      targetPort: 3000 # Port the container listens on
  selector:
    app: nextjs-app