apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-nginx-config
data:
  nginx.conf: |
    worker_processes auto;

    events {
        worker_connections 4096;  # Increase worker connections for high traffic
        multi_accept on;          # Accept multiple connections at once
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        # Increase buffer sizes for high traffic
        proxy_buffers 16 32k;
        proxy_buffer_size 64k;

        # Timeouts for WebSocket connections
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;

        # Keepalive settings
        keepalive_timeout 65;
        keepalive_requests 10000;

        # Disable proxy buffering for WebSockets
        proxy_buffering off;

        # Define Kubernetes DNS resolver
        resolver 10.96.0.10 valid=300s;

        # Enhanced log format for incoming requests
        log_format incoming '$remote_addr - $remote_user [$time_local] '
                          '"$request" $status $body_bytes_sent '
                          '"$http_referer" "$http_user_agent" '
                          'Host: $host '
                          'Incoming-Request-ID: $request_id';

        # Enhanced log format for proxy requests
        log_format proxy    '$remote_addr - $remote_user [$time_local] '
                          '"$request" $status $body_bytes_sent '
                          'Upstream: $target '
                          'Response-Time: $upstream_response_time '
                          'Request-ID: $request_id';

        # Main access and error logs
        access_log  /var/log/nginx/access.log  incoming;
        error_log   /var/log/nginx/error.log warn;

        # CORS map for allowed origins
        map $http_origin $cors_allow_origin {
            default "";
            "http://localhost:3000" $http_origin;
            "http://localhost:3001" $http_origin;
            "https://iamanshik.online" $http_origin;
            "https://api.iamanshik.online" $http_origin;
            "~^https?://.*\.iamanshik\.online$" $http_origin;
            # Add any other domains you need
        }

        server {
            listen 80;
            server_name ~^(?<service>[a-zA-Z0-9-]+)-(?<port>\d+)\.code\.iamanshik\.online$;

            set $target '';

            # Generate unique request ID
            # Moved inside location block

            # Handle preflight requests
            if ($request_method = 'OPTIONS') {
                return 204;
            }

            location / {
                # Generate unique request ID
                add_header X-Request-ID $request_id;

                # CORS headers
                add_header 'Access-Control-Allow-Origin' $cors_allow_origin always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept, Authorization' always;
                add_header 'Access-Control-Allow-Credentials' 'true' always;
                add_header 'Access-Control-Max-Age' '3600' always;

                access_log /var/log/nginx/proxy.log proxy;

                access_by_lua_block {
                    local service = ngx.var.service
                    local port = ngx.var.port

                    if service and port then
                        ngx.var.target = "http://" .. service .. ".default.svc.cluster.local:" .. port
                        ngx.log(ngx.INFO, "Proxying to: " .. ngx.var.target)
                    else
                        ngx.log(ngx.ERR, "Invalid hostname pattern")
                        ngx.exit(404)
                    end

                    -- Handle preflight (OPTIONS) requests with CORS headers
                    if ngx.req.get_method() == "OPTIONS" then
                        ngx.header["Access-Control-Allow-Origin"] = ngx.var.cors_allow_origin
                        ngx.header["Access-Control-Allow-Methods"] = "GET, POST, PUT, DELETE, OPTIONS"
                        ngx.header["Access-Control-Allow-Headers"] = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
                        ngx.header["Access-Control-Allow-Credentials"] = "true"
                        ngx.header["Access-Control-Max-Age"] = "3600"
                        ngx.header["Content-Type"] = "text/plain charset=UTF-8"
                        ngx.header["Content-Length"] = "0"
                        ngx.exit(204)
                    end
                }

                proxy_pass $target;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Request-ID $request_id;

                # WebSocket support
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }
        }
    }
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy
spec:
  replicas: 5  # Initial number of replicas
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      containers:
      - name: nginx
        image: openresty/openresty:alpine
        ports:
        - containerPort: 80
        # resources:
        #   requests:
        #     cpu: "500m"  # 0.5 CPU
        #     memory: "512Mi"
        #   limits:
        #     cpu: "1000m"  # 2 CPU
        #     memory: "2Gi"
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          subPath: nginx.conf
        - name: nginx-logs
          mountPath: /var/log/nginx
      volumes:
      - name: config-volume
        configMap:
          name: custom-nginx-config
      - name: nginx-logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-reverse-proxy
  type: ClusterIP  # Use LoadBalancer if exposing externally

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-reverse-proxy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-reverse-proxy
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80