/**
 * @fileoverview gRPC-Web generated client stub for ideserver
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: main.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.ideserver = require('./main_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ideserver.GreeterClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ideserver.GreeterPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ideserver.HelloRequest,
 *   !proto.ideserver.HelloReply>}
 */
const methodDescriptor_Greeter_SayHello = new grpc.web.MethodDescriptor(
  '/ideserver.Greeter/SayHello',
  grpc.web.MethodType.UNARY,
  proto.ideserver.HelloRequest,
  proto.ideserver.HelloReply,
  /**
   * @param {!proto.ideserver.HelloRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ideserver.HelloReply.deserializeBinary
);


/**
 * @param {!proto.ideserver.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ideserver.HelloReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ideserver.HelloReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ideserver.GreeterClient.prototype.sayHello =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ideserver.Greeter/SayHello',
      request,
      metadata || {},
      methodDescriptor_Greeter_SayHello,
      callback);
};


/**
 * @param {!proto.ideserver.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ideserver.HelloReply>}
 *     Promise that resolves to the response
 */
proto.ideserver.GreeterPromiseClient.prototype.sayHello =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ideserver.Greeter/SayHello',
      request,
      metadata || {},
      methodDescriptor_Greeter_SayHello);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ideserver.HelloRequest,
 *   !proto.ideserver.HelloReply>}
 */
const methodDescriptor_Greeter_SayHelloAgain = new grpc.web.MethodDescriptor(
  '/ideserver.Greeter/SayHelloAgain',
  grpc.web.MethodType.UNARY,
  proto.ideserver.HelloRequest,
  proto.ideserver.HelloReply,
  /**
   * @param {!proto.ideserver.HelloRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ideserver.HelloReply.deserializeBinary
);


/**
 * @param {!proto.ideserver.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ideserver.HelloReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ideserver.HelloReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ideserver.GreeterClient.prototype.sayHelloAgain =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ideserver.Greeter/SayHelloAgain',
      request,
      metadata || {},
      methodDescriptor_Greeter_SayHelloAgain,
      callback);
};


/**
 * @param {!proto.ideserver.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ideserver.HelloReply>}
 *     Promise that resolves to the response
 */
proto.ideserver.GreeterPromiseClient.prototype.sayHelloAgain =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ideserver.Greeter/SayHelloAgain',
      request,
      metadata || {},
      methodDescriptor_Greeter_SayHelloAgain);
};


module.exports = proto.ideserver;

