/**
 * @fileoverview gRPC-Web generated client stub for ideserver
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: main.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.ideserver = require('./main_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ideserver.RunnerServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ideserver.RunnerServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ideserver.MakeContainerRequest,
 *   !proto.ideserver.MakeContainerResponse>}
 */
const methodDescriptor_RunnerService_MakeContainer = new grpc.web.MethodDescriptor(
  '/ideserver.RunnerService/MakeContainer',
  grpc.web.MethodType.UNARY,
  proto.ideserver.MakeContainerRequest,
  proto.ideserver.MakeContainerResponse,
  /**
   * @param {!proto.ideserver.MakeContainerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ideserver.MakeContainerResponse.deserializeBinary
);


/**
 * @param {!proto.ideserver.MakeContainerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ideserver.MakeContainerResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ideserver.MakeContainerResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ideserver.RunnerServiceClient.prototype.makeContainer =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ideserver.RunnerService/MakeContainer',
      request,
      metadata || {},
      methodDescriptor_RunnerService_MakeContainer,
      callback);
};


/**
 * @param {!proto.ideserver.MakeContainerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ideserver.MakeContainerResponse>}
 *     Promise that resolves to the response
 */
proto.ideserver.RunnerServicePromiseClient.prototype.makeContainer =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ideserver.RunnerService/MakeContainer',
      request,
      metadata || {},
      methodDescriptor_RunnerService_MakeContainer);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ideserver.ConnectContainerRequest,
 *   !proto.ideserver.ConnectContainerResponse>}
 */
const methodDescriptor_RunnerService_ConnectContainer = new grpc.web.MethodDescriptor(
  '/ideserver.RunnerService/ConnectContainer',
  grpc.web.MethodType.UNARY,
  proto.ideserver.ConnectContainerRequest,
  proto.ideserver.ConnectContainerResponse,
  /**
   * @param {!proto.ideserver.ConnectContainerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ideserver.ConnectContainerResponse.deserializeBinary
);


/**
 * @param {!proto.ideserver.ConnectContainerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ideserver.ConnectContainerResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ideserver.ConnectContainerResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ideserver.RunnerServiceClient.prototype.connectContainer =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ideserver.RunnerService/ConnectContainer',
      request,
      metadata || {},
      methodDescriptor_RunnerService_ConnectContainer,
      callback);
};


/**
 * @param {!proto.ideserver.ConnectContainerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ideserver.ConnectContainerResponse>}
 *     Promise that resolves to the response
 */
proto.ideserver.RunnerServicePromiseClient.prototype.connectContainer =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ideserver.RunnerService/ConnectContainer',
      request,
      metadata || {},
      methodDescriptor_RunnerService_ConnectContainer);
};


module.exports = proto.ideserver;

