// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RunnerServiceClient is the client API for RunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnerServiceClient interface {
	MakeContainer(ctx context.Context, in *MakeContainerRequest, opts ...grpc.CallOption) (*MakeContainerResponse, error)
	DeleteContainer(ctx context.Context, in *DeleteContainerRequest, opts ...grpc.CallOption) (*DeleteContainerResponse, error)
	GetContainerStatus(ctx context.Context, in *ContainerStatusRequest, opts ...grpc.CallOption) (RunnerService_GetContainerStatusClient, error)
}

type runnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerServiceClient(cc grpc.ClientConnInterface) RunnerServiceClient {
	return &runnerServiceClient{cc}
}

func (c *runnerServiceClient) MakeContainer(ctx context.Context, in *MakeContainerRequest, opts ...grpc.CallOption) (*MakeContainerResponse, error) {
	out := new(MakeContainerResponse)
	err := c.cc.Invoke(ctx, "/ideserver.RunnerService/MakeContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) DeleteContainer(ctx context.Context, in *DeleteContainerRequest, opts ...grpc.CallOption) (*DeleteContainerResponse, error) {
	out := new(DeleteContainerResponse)
	err := c.cc.Invoke(ctx, "/ideserver.RunnerService/DeleteContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) GetContainerStatus(ctx context.Context, in *ContainerStatusRequest, opts ...grpc.CallOption) (RunnerService_GetContainerStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RunnerService_serviceDesc.Streams[0], "/ideserver.RunnerService/GetContainerStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &runnerServiceGetContainerStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RunnerService_GetContainerStatusClient interface {
	Recv() (*ContainerStatusResponse, error)
	grpc.ClientStream
}

type runnerServiceGetContainerStatusClient struct {
	grpc.ClientStream
}

func (x *runnerServiceGetContainerStatusClient) Recv() (*ContainerStatusResponse, error) {
	m := new(ContainerStatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RunnerServiceServer is the server API for RunnerService service.
// All implementations must embed UnimplementedRunnerServiceServer
// for forward compatibility
type RunnerServiceServer interface {
	MakeContainer(context.Context, *MakeContainerRequest) (*MakeContainerResponse, error)
	DeleteContainer(context.Context, *DeleteContainerRequest) (*DeleteContainerResponse, error)
	GetContainerStatus(*ContainerStatusRequest, RunnerService_GetContainerStatusServer) error
	mustEmbedUnimplementedRunnerServiceServer()
}

// UnimplementedRunnerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRunnerServiceServer struct {
}

func (UnimplementedRunnerServiceServer) MakeContainer(context.Context, *MakeContainerRequest) (*MakeContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeContainer not implemented")
}
func (UnimplementedRunnerServiceServer) DeleteContainer(context.Context, *DeleteContainerRequest) (*DeleteContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContainer not implemented")
}
func (UnimplementedRunnerServiceServer) GetContainerStatus(*ContainerStatusRequest, RunnerService_GetContainerStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method GetContainerStatus not implemented")
}
func (UnimplementedRunnerServiceServer) mustEmbedUnimplementedRunnerServiceServer() {}

// UnsafeRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServiceServer will
// result in compilation errors.
type UnsafeRunnerServiceServer interface {
	mustEmbedUnimplementedRunnerServiceServer()
}

func RegisterRunnerServiceServer(s *grpc.Server, srv RunnerServiceServer) {
	s.RegisterService(&_RunnerService_serviceDesc, srv)
}

func _RunnerService_MakeContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).MakeContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ideserver.RunnerService/MakeContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).MakeContainer(ctx, req.(*MakeContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_DeleteContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).DeleteContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ideserver.RunnerService/DeleteContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).DeleteContainer(ctx, req.(*DeleteContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_GetContainerStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContainerStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServiceServer).GetContainerStatus(m, &runnerServiceGetContainerStatusServer{stream})
}

type RunnerService_GetContainerStatusServer interface {
	Send(*ContainerStatusResponse) error
	grpc.ServerStream
}

type runnerServiceGetContainerStatusServer struct {
	grpc.ServerStream
}

func (x *runnerServiceGetContainerStatusServer) Send(m *ContainerStatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _RunnerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ideserver.RunnerService",
	HandlerType: (*RunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeContainer",
			Handler:    _RunnerService_MakeContainer_Handler,
		},
		{
			MethodName: "DeleteContainer",
			Handler:    _RunnerService_DeleteContainer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetContainerStatus",
			Handler:       _RunnerService_GetContainerStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "main.proto",
}
